### ISSUE TITLE
OBS can't connect to stream-m server

### ISSUE THREAD

**Issue by gburgwardt** [vbence/stream-m#13]
Love the work being done on this, would like to contribute somehow, but the first step is to just get it running -

I've installed the JDK and netbeans, to compile the code. That part went well, and now I'm running a server with the default settings. I try and connect with OBS from windows to the server (also running on windows) and OBS fails to connect.

I am pointing OBS to http://localhost:8081/publish/first?password=secret 
But according to the OBS log the connection fails, here's the relevant part

```
:24:32:   Interface: Software Loopback Interface 1 (type 24, 1073 mbps)

17:24:32: Completed handshake with http://localhost:8081/publish/first?password=secret in 3 ms.

17:24:42: Total frames encoded: 330, total frames duplicated: 1 (0.30%)

17:24:42: Total frames rendered: 355, number of late frames: 0 (0.00%) (it's okay for some frames to be late)

17:24:42: librtmp error: RTMPSockBuf_Fill, recv returned -1. GetSockError(): 10053 (An established connection was aborted by the software in your host machine.)

17:24:42: Connection to http://localhost:8081/publish/first?password=secret failed: Could not access the specified channel or stream key.  This could be because the key/channel is invalid, or because the server still thinks you are logged in.

17:24:42: 

17:24:42: RTMPSockBuf_Fill, recv returned -1. GetSockError(): 10053 (An established connection was aborted by the software in your host machine.)

17:24:42: 

17:24:42: ~RTMPPublisher: Packet flush completed in 0 ms

```

Happy to test whatever needed, though likely I am just plugging in settings incorrectly.

I have tried basically every variation I can think of to connect to with OBS, but none work

**Comment by vbence** [comment]
Hi and thanks for the feedback. The stream's URL should just be just `first?secret` the `password=` part is only needed in case of WebM publishing.

**Comment by gburgwardt** [comment]
http://i.imgur.com/Nzajega.png

There's a screenshot of all the relevant settings, I believe. 

```
C:\Users\Garrett\Desktop\stream-m-master\dist>java -jar stream-m.jar server.prop
erties
Exception in thread "Thread-2" java.lang.RuntimeException: java.net.SocketExcept
ion: Connection reset
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:78)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:70)
        ... 1 more
Exception in thread "Thread-9" java.lang.RuntimeException: java.net.SocketExcept
ion: Connection reset
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:78)
        at org.czentral.minihttp.HTTPRequestLoader.loadRequestLine(HTTPRequestLo
ader.java:241)
        at org.czentral.minihttp.HTTPRequestLoader.getPathName(HTTPRequestLoader
.java:119)
        at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:106)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:70)
        ... 3 more
```

And there is the text in the cmd line.

So it seems like it's connecting but the server is throwing some sort of error. I'm not familiar with java so I'll leave it to interpret that haha

**Comment by vbence** [comment]
The port should be 8081 (that is the rtmp server by  default. 8080 is the HTTP, it is only for watching). ;)

**Comment by gburgwardt** [comment]
Yep, I've tried every combination of rtmp:// / http:// and  8080/8081

All give the same result. Thank you for your quick response!

**Comment by vbence** [comment]
Can you please try the following URL:
rtmp://localhost:8081/publish/first?secret

... and see what happens.

**Comment by gburgwardt** [comment]
http://i.imgur.com/yVYLBku.png

Same result afaict

**Comment by vbence** [comment]
Okay.. how about another try - i feel strongly about this one :)
URL: `rtmp://localhost:8081/publish`
Stream key: `first?secret`

**Comment by gburgwardt** [comment]
Copied exactly what you told me, no change :(

**Comment by gburgwardt** [comment]
Wait, suddenly it worked (after restarting OBS a few times)

The player loads in firefox, but doesn't appear to play anything. Progress, anyway

**Comment by vbence** [comment]
Try playback in Chrome. The player is more like a howto-demo. I'll take a look at Firefox when I have some time.

**Comment by gburgwardt** [comment]
And more refreshing of everything, it seems to be working! About 50s of delay, but working.

Looking through the server.properties file, I don't see much in the way of configuration options - can I make multiple streams by copying the line that appears to make the "first" stream?

More generally, could I donate to this project/contract you to add some specific features? Hell, if you're willing I'd happily hire you to work on this with the goal of making it an acceptable alternative to something like twitch.

Feel free to message me here (does github do PMs?) or email me at garrett dot burgwardt at gmail
