### ISSUE TITLE
SHORT_HEAD_WITHOUT_HISTORY.  Error message

### ISSUE THREAD

**Issue by leon456** [vbence/stream-m#15]
The file(output.webm) can play via VLC.
I test 

D:\ffmpeg-20150806-git-8024002-win64-static\bin>ffmpeg.exe -re -i output.webm -v
codec copy -acodec copy -f webm http://localhost:8081/publish/first?password=sec
ret

I can see the fragment stream to server

Output #0, webm, to 'http://localhost:8081/publish/first?password=secret':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: vp8, yuv420p, 320x240 [SAR 1:1 DAR 4:3], q=2-31, 30 fps,
 30 tbr, 1k tbn, 1k tbc (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
frame=   17 fps=0.0 q=-1.0 size=       0kB time=00:00:00.53 bitrate=   6.6kbits/
frame=   32 fps= 32 q=-1.0 size=      33kB time=00:00:01.03 bitrate= 257.6kbits/
frame=   47 fps= 31 q=-1.0 size=      33kB time=00:00:01.53 bitrate= 173.6kbits/
frame=   62 fps= 31 q=-1.0 size=      45kB time=00:00:02.03 bitrate= 181.6kbits/
frame=   77 fps= 31 q=-1.0 size=      45kB time=00:00:02.53 bitrate= 145.8kbits/
frame=   92 fps= 31 q=-1.0 size=      45kB time=00:00:03.03 bitrate= 121.8kbits/
frame=  107 fps= 30 q=-1.0 size=      70kB time=00:00:03.53 bitrate= 161.8kbits/
frame=  123 fps= 31 q=-1.0 size=      70kB time=00:00:04.06 bitrate= 140.6kbits/

but in server console,I get below error message

Exception in thread "Thread-10" java.lang.RuntimeException: Unsupported feature
encountered: SHORT_HEAD_WITHOUT_HISTORY.

How can I fix this issue?

**Comment by vbence** [comment]
The message SHORT_HEAD_WITHOUT_HISTORY comes in RTMP mode. It was probably left from a previous ffmpeg run. If you can watch the stream in your browser on `http://localhost/consume/first` then there is no problem.
