### ISSUE TITLE
Max browser numbers and IE 

### ISSUE THREAD

**Issue by xljeff** [vbence/stream-m#16]
Hi, thanks for this good tool !
(1) I want to have a Stress Testing on my server hardware and network use stream-m ,an easy php code to open 10 video tags in one page,  but only 6 success in one computer, i can keep open this page to more then 10 computers , always 6 video can load on page in each computer , i can't find any setting about this,and there is no any firewall or special network connection setting on server or client site,  is there any way to load more tags in one page ?
----------------------------Stress Testing web page (remove some flag for display)
<?php
    for($i=0;$i<10;$i++) {
        echo video id="movie" controls="true" width="230" height="150" autoplay preload poster="preload.jpg"
        echo source src="http://10.10.10.1:8083/consume/first"
        echo /video
    }
?>
-----------------------------Ffmpeg command
./ffmpeg1 -i "rtmp://stream_source_url:1935/spliveorigin/Stream_REAL" -acodec libvorbis -ab 64k -vsync cfr -r 20 -vcodec libvpx -vb 448k -g 52 -lag-in-frames 1 -slices 4 -deadline realtime -bufsize 512 -f webm "http://10.10.10.1:8083/publish/first?password=secret"

(2) Same url open on IE , can't work , is that normal ?

Thanks for your help !

**Comment by vbence** [comment]
Hi Jeff,
If you want to stress-test the sinple`consume/first` URL playing (instewad of the MediaSource method), you can emulate the same behavior with much less resources.

Essentially, from the server's perspective, you don't have to **play** the stream you just have to download it on many concurrent clients. You can do this something like the following command:

    ffmpeg -i http://10.10.10.1:8083/consume/first -acodec copy -vcodec copy -f null dummy.null

This will not decode the stream, just download it, so it is much easier on the client machine.

Yep. IE has no WebM support. It is promised though for the future:
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6508954-native-webm

**Comment by xljeff** [comment]
Hi vbence, 

(1) thanks, this information is very helpful !

(2) I am using M3U8 for IOS / Android , Stream-M for Chrome , is there anyway can service IE user ? (sorry. maybe this issue is not for This case but i really hope can get one or few format can service all users.!)

Thanks again !
