### ISSUE TITLE
Publishing Video via URL

### ISSUE THREAD

**Issue by joejoe9982** [vbence/stream-m#20]
is it possible for an end-user just to open a URL, like:
https://simpl.info/getusermedia/sources/
and the video using the users webcam is being published?

**Comment by vbence** [comment]
Currently no, at least not natively. The sever has RTMP input, so a flash application embedded in a webpage can theoretically send a stream. The problem with that is that AAC encoding (for audio) is not currently supported by the flash player (and does not seem to be in the future).

Also currently only CFR is supported, so you will need a source (webcam) which sends frames in constant intervals (camcorder and a HDMI input card should do). Current consumer webcams dynamically set the exposure time according to lighting conditions which will result in variable frame rate (VFR).
