### ISSUE TITLE
java.lang.RuntimeException / connection reset

### ISSUE THREAD

**Issue by kraja** [vbence/stream-m#22]
Hi,
i try run stream-m - i unpack archive and run "java -jar stream-m.jar server.properties" (server.properties is default configuration, i do only copy server.properties.sample). 

I try to connect from flash media encoder and ffmpeg, after i try connect, i get error:
`root@debian-2gb-fra1-01:~# java -jar stream-m.jar server.properties
Processor finished.
Exception in thread "Thread-2" java.lang.RuntimeException: java.net.SocketException: Connection reset
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:81)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:71)
        ... 1 more
`

Flash media encoder immediately shutdown.
I try too ffmpeg:
 ffmpeg -re -i aaa.flv -f flv rtmp://46.101.226.239:8081/publish/testing

but i get too error...
on ffmpeg side:

```
rtmp server sent error
RTMP_ReadPacket, failed to read RTMP packet header
rtmp://46.101.226.239:8081/publish/testing: Operation not permitted
```

on stream-m server side:
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Processor finished.
Connection closed.

I run on debian linux - jessie - installed "openjdk-7-jre openjdk-7-jre default-jre default-jre-headless" packages.

Can you have any tips, please? Thx

**Comment by kraja** [comment]
![image](https://cloud.githubusercontent.com/assets/125937/13582180/18b3c48e-e4ab-11e5-9d69-f259ff36cffd.png)

**Comment by vbence** [comment]
Hi, the first thing I can think of if the file contains a H.264 and AAC streams. Please make a trial run with the webcam example, that is guaranteed to be the right encoding. If it works, then your sample file probably needs transcoding.

**Comment by kraja** [comment]
Hi, thanks for fast reply. I trying h264 and vp6 - this two formats supported by adobe flash media encoder. Or, i dont understand, what format i must use as right input? Thanks

**Comment by vbence** [comment]
I recommend you do the first round of tests with ffmpeg, and move away from the example one step at a time.
