### ISSUE TITLE
Connecting via RTMP

### ISSUE THREAD

**Issue by TorchwoodPL** [vbence/stream-m#24]
When I try to connect via RTMP to server I get:

> sie 07, 2016 9:06:19 PM org.czentral.minirtmp.ApplicationContext processMessage
> WARNING: /192.168.2.100:49347
> java.lang.UnsupportedOperationException: Unknown type ID: 6
>         at org.czentral.minirtmp.AMFDecoder.readMixed(AMFDecoder.java:155)
>         at org.czentral.minirtmp.AMFDecoder.readObject(AMFDecoder.java:104)
>         at org.czentral.minirtmp.AMFDecoder.readMixed(AMFDecoder.java:148)
>         at org.czentral.minirtmp.ApplicationContext.readCommand(ApplicationContext.java:210)
>         at org.czentral.minirtmp.ApplicationContext.processMessage(ApplicationContext.java:153)
>         at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:133)
>         at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:211)
>         at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
>         at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
>         at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:96)
> 
> Exception in thread "Thread-10" java.lang.RuntimeException: java.lang.UnsupportedOperationException: Unknown type ID: 6
>         at org.czentral.minirtmp.ApplicationContext.processMessage(ApplicationContext.java:202)
>         at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:133)
>         at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:211)
>         at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
>         at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
>         at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:96)
> Caused by: java.lang.UnsupportedOperationException: Unknown type ID: 6
>         at org.czentral.minirtmp.AMFDecoder.readMixed(AMFDecoder.java:155)
>         at org.czentral.minirtmp.AMFDecoder.readObject(AMFDecoder.java:104)
>         at org.czentral.minirtmp.AMFDecoder.readMixed(AMFDecoder.java:148)
>         at org.czentral.minirtmp.ApplicationContext.readCommand(ApplicationContext.java:210)
>         at org.czentral.minirtmp.ApplicationContext.processMessage(ApplicationContext.java:153)
>         ... 5 more
> Exception in thread "Thread-8" Exception in thread "Thread-9" Exception in thread "Thread-7" java.lang.NullPointerException
>         at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)
> java.lang.NullPointerException
>         at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)
> java.lang.NullPointerException
>         at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)

**Comment by aderal000** [comment]
when I try to connect via OBS 0.15.2 I get:

> D:\Projekty\stream-m\dist>java -jar stream-m.jar server.properties
> metadata: [@setDataFrame, onMetaData, {framerate=30.0, audiocodecid=mp4a, audiodatarate=160.0, videodatarate=2500.0, audiosamplesize=16.0, audiosamplerate=44100.0, encoder=obs-output module (libobs version 0.15.2), duration=0.0, videocodecid=avc1, fileSize=0.0, stereo=true, width=1092.0, audiochannels=2.0, height=614.0}]
> sie 07, 2016 9:31:15 PM org.czentral.minirtmp.ApplicationContext processMessage
> WARNING: /0:0:0:0:0:0:0:1:65070
> java.lang.RuntimeException: SPS/PPS expected, got type 4.
>         at org.czentral.incubator.streamm.PublisherAppInstance.mediaChunk(PublisherAppInstance.java:338)
>         at org.czentral.minirtmp.ApplicationContext.processMessage(ApplicationContext.java:191)
>         at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:140)
>         at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:211)
>         at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
>         at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
>         at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:96)
> 
> Exception in thread "Thread-3" java.lang.RuntimeException: java.lang.RuntimeException: SPS/PPS expected, got type 4.
>         at org.czentral.minirtmp.ApplicationContext.processMessage(ApplicationContext.java:202)
>         at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:140)
>         at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:211)
>         at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
>         at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
>         at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:96)
> Caused by: java.lang.RuntimeException: SPS/PPS expected, got type 4.
>         at org.czentral.incubator.streamm.PublisherAppInstance.mediaChunk(PublisherAppInstance.java:338)
>         at org.czentral.minirtmp.ApplicationContext.processMessage(ApplicationContext.java:191)
>         ... 5 more
> Exception in thread "Thread-2" java.lang.NullPointerException
>         at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)

**Comment by vbence** [comment]
The new RTMP parser should probably fix issues like this.
