### ISSUE TITLE
What's Wrong? Exception in thread "Thread-2" java.lang.RuntimeException: Unable to serialize filed [org.czentral.format.mp4.MovieDataBox#content].

### ISSUE THREAD

**Issue by MarsZone** [vbence/stream-m#26]
First of all.. Thank you make this project. But It seems not working...

![wrong](https://cloud.githubusercontent.com/assets/3784198/18245504/2d706996-7398-11e6-9ecf-6f390dc5d948.jpg)

![2](https://cloud.githubusercontent.com/assets/3784198/18245479/10cabda0-7398-11e6-9da2-abe326314fc3.jpg)

**Comment by Fripplebubby** [comment]
For anyone else having this problem, I was able to work around it by constraining the bitrate. When leaving the video bitrate unconstrained, it was encoding at 2 megabits and higher, and this produced the crash.
![highbitrate](https://user-images.githubusercontent.com/3044352/27310115-e46be93a-550c-11e7-82a7-db4baa69d3a9.png)

By adjusting my ffmpeg setting to limit the bitrate to 1M, as below: 
![megabit](https://user-images.githubusercontent.com/3044352/27310144-08039df2-550d-11e7-80a7-09e8eca2169f.png)
The crash does not occur.

**Comment by vbence** [comment]
You are not enforcing the keyframe interval (`-g` switch). Please read the readme about the fragments.
