### ISSUE TITLE
Partial header (buffered sample too small).

### ISSUE THREAD

**Issue by neuroscr** [vbence/stream-m#3]
java.lang.RuntimeException: Partial header (buffered sample too small).
	at org.czentral.incubator.streamm.EBMLElement.<init>(EBMLElement.java:61)
	at org.czentral.incubator.streamm.HeaderDetectionState.process(HeaderDetectionState.java:62)
	at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
	at org.czentral.incubator.streamm.StreamInput.run(StreamInput.java:47)
	at org.czentral.incubator.streamm.web.PublisherResource.serve(PublisherResource.java:98)
	at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:124)

using libav

# avconv -re -i rtmp://localhost/live/test -vcodec libvpx -acodec libvorbis -s 320x240 -r 29.97 -threads 64 -f webm http://localhost:8090/publish/first?password=secret
avconv version 0.8.16-6:0.8.16-1, Copyright (c) 2000-2014 the Libav developers
  built on Sep 16 2014 23:10:48 with gcc 4.7.2
Metadata:
  Server                NGINX RTMP (github.com/arut/nginx-rtmp-module)
  width                 1440.00
  height                900.00
  displayWidth          1440.00
  displayHeight         900.00
  duration              0.00
  framerate             60.00
  fps                   60.00
  videodatarate         250.00
  videocodecid          0.00
  audiodatarate         128.00
  audiocodecid          0.00
  profile               
  level                 
[flv @ 0x1e19b20] Estimating duration from bitrate, this may be inaccurate
Input #0, flv, from 'rtmp://localhost/live/test':
  Duration: N/A, start: 1384.489000, bitrate: N/A
    Stream #0.0: Video: h264 (High), yuv420p, 1440x900, 59.94 tbr, 1k tbn, 120 tbc
    Stream #0.1: Audio: aac, 44100 Hz, stereo, s16
[buffer @ 0x1e1efc0] w:1440 h:900 pixfmt:yuv420p
[scale @ 0x1efdb60] w:1440 h:900 fmt:yuv420p -> w:320 h:240 fmt:yuv420p flags:0x4
[libvpx @ 0x1e1e420] v1.1.0
Output #0, webm, to 'http://localhost:8090/publish/first?password=secret':
  Metadata:
    encoder         : Lavf53.21.1
    Stream #0.0: Video: libvpx, yuv420p, 320x240, q=-1--1, 200 kb/s, 1k tbn, 29.97 tbc
    Stream #0.1: Audio: libvorbis, 44100 Hz, stereo, s16
Stream mapping:
  Stream #0:0 -> #0:0 (h264 -> libvpx)
  Stream #0:1 -> #0:1 (aac -> libvorbis)

I have to restart avconv over until I don't get that error and then things work until I need to restart avconv.

What other info do you need?

**Comment by vbence** [comment]
Thanks for the report. I pushed a fix to the branch hotfix-gh3:
https://github.com/vbence/stream-m/tree/hotfix-gh3

You can give it a try, or let me know if you need a compiled binary.

**Comment by neuroscr** [comment]
Yes, a binary would be a big help. Not familiar with the build system you have, sounds like I might need an IDE. Since this a remote server, I only have access to command line. So if there's a debian package or build system I can download and compile to build your project. Otherwise a binary would be great.

And thanks for the quick response.

**Comment by vbence** [comment]
Great, so if I'm understanding you correctly, this fixed it. (The *"I was able to build but getting:"* part is a bit confusing :)

**Comment by fflo** [comment]
I'm facing the same problem:
@vbence Is it possible that you publish an updated release fixing this issue?
Thx.

**Comment by vbence** [comment]
Merged and added to the release:
https://github.com/vbence/stream-m/releases
