### ISSUE TITLE
Stuck at 4-5 seconds

### ISSUE THREAD

**Issue by nezcich** [vbence/stream-m#32]
Im streaming with obs . is the error im getting.
Im able to view only 4-5 seconds of streaming in http://localhost:8080/consume/first.
im streaming through obs rtmp.
After 5 seconds the video is ended and stuck (no error on console either) 

Im not doing anything with ffmpeg. Do i need to use ffmpeg ? ( if i dont want  to store the streamed recording)

![screenshot from 2017-02-04 21-07-53](https://cloud.githubusercontent.com/assets/8493784/22619612/6623c316-eb1e-11e6-8b57-0c305a66019d.png)

**Comment by vbence** [comment]
`ArrayIndexOutOfBoundsException` inside `MovieDataBox` means the fragment is too large. There is a 2 megabyte (+64k metadata) hard limit per track.

https://github.com/vbence/stream-m/blob/1380eaf5c74c8a331e7c59568178faca64d3e97f/src/main/java/org/czentral/incubator/streamm/MovieFragment.java#L30
