### ISSUE TITLE
how to run on a debian wheezy headless server?

### ISSUE THREAD

**Issue by allegfede** [vbence/stream-m#35]
hello, i'm a real nub in the java enviroment, so i had some question to avoid making some mess.
I run a VPS where an icecast2 provide audio streaming to clients.

Now i wish to expand the server and add video features.

Stream-m seems to be interesting so i dig the weeb for an open source video streaming server that handles h264 content (i got video from an hauppauge hd pvr h264 hardware capture card).

The question is: what i had to install in the server to compile/run stream-m?

thanks a lot,

Federico

**Comment by allegfede** [comment]
this is the way i send the video:
#-------opzioni per streamM server sulla vps ---------------
RTMP_URL_streamM=rtmp://machine_name_on.ovh.net:8081/publish/first?
SECRET=thepasswordichoose

#seems to connect and feeds the server for 350 - 500 frames .. thena stucks
ffmpeg  -y -re -f mpegts -i /dev/video0  -c:v copy -c:a copy -bsf:a aac_adtstoasc -f flv   "${RTMP_URL_streamM}${SECRET}"

this other instead is the string i run on the server (and the console output):
java -jar stream-m.jar server.properties

Processor finished.
metadata: [@setDataFrame, onMetaData, {audiocodecid=10.0, audiosamplerate=48000.0, width=720.0, videodatarate=0.0, videocodecid=7.0, filesize=0.0, duration=0.0, height=576.0, audiodatarate=124.8779296875, stereo=true, audiosamplesize=16.0, framerate=25.0, encoder=Lavf56.4.101}]
Exception in thread "Thread-2" java.lang.ArrayIndexOutOfBoundsException: 0
	at org.czentral.incubator.streamm.PublisherAppInstance.mediaChunk(PublisherAppInstance.java:318)
	at org.czentral.minirtmp.ApplicationContext.processMessage(ApplicationContext.java:179)
	at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:129)
	at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:206)
	at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
	at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
	at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)

**Comment by vbence** [comment]
Hi, my first idea would be that the card's keyframe interval is not optimized for streaming. There must be a keyframe (h264 intra frame) in every like 2 seconds, so the server could build fragments (individually playable groups of picutres).

I didn't have much success with streaming directly from hardware encoders under Linux (if you don't count Intel's QuickSync). I'd recommend you save your ffmpeg output to a file you can inspect (for keyframe interval and similar settings). Then check out the `v4l2-ctl` command and if your settings there have indeed an effect to the output. - If you manage to fine-tune it and you're satisfied with the parameters then give stream-m another try.

If you come up with the magic ingredients please share :)

**Comment by allegfede** [comment]
i tested the whole stuff with the univac.webm sample clip and this ffmpeg command:

ffmpeg  -re  -i univac.webm  -c:v copy  -c:a copy  -f webm  "rtmp://myvps.ovh.net:8081/publish/first?passsegretapervideostreaming"

but, altought stream-m server reacts to the incoming streming, i cannot see nothing in local browser pointing to the vps: http://myvps.ovh.net:8080/consume/first
returns: Stream Not Running

and the player page accepts the play button click, but cacheing forever and nothing appears ...
![screenshot from 2018-02-07 19-55-43](https://user-images.githubusercontent.com/1426650/35936319-2eab155a-0c43-11e8-96e9-a196f52f870e.png)

**Comment by vbence** [comment]
The webm and h264 pipelines are quite different, your test above should look:
```
ffmpeg -re -i univac.mp4 -c:v copy -c:a copy -f flv "rtmp://myvps.ovh.net:8081/publish/first?passsegretapervideostreaming"
```

You can create the mp4 file if you already have the other version with:
```
ffmpeg -i univac.webm \
-g 52 -strict experimental -acodec aac -ab 56k -vcodec libx264 -vb 452k \
-profile:v high -level 40 -r 16 \
-f mov univac.mp4
```

(i couln't test the commands, but i hope they can show you the direction)

**Comment by allegfede** [comment]
THIS WORKS :D
 ffmpeg -re -i univac.webm -c:v copy -c:a copy -f webm http://myvps.ovh.net:8080/publish/first?password=passsegretapervideostreaming

Passing from h264 to webm and back in scripts drove to some typos :D

testing the h264 ...

**Comment by allegfede** [comment]
converting teh webm to h264 with the command u give:

ffmpeg -i univac.webm \
-g 52 -strict experimental -acodec aac -ab 56k -vcodec libx264 -vb 452k \
-profile:v high -level 40 -r 16 \
-f mov univac.mp4

and streaming it with:
ffmpeg -re -i univac.mp4 -c:v copy -c:a copy -f flv "rtmp://myvps.ovh.net:8081/publish/first?passsegretapervideostreaming"

WORKED WELL!

PS: note that the port working is **8080** for the WEBM and the **8081** for the H264 .... is that normal?

**Comment by allegfede** [comment]
this other command instead:

ffmpeg -y -re -f mpegts -i /dev/video0  -c:v copy -g 100 -c:a copy -bsf:a aac_adtstoasc -f flv "rtmp://myvps.ovh.net:8081/publish/first?passsegretapervideostreaming"

drives to and endless caching from the server first page and the feeding process stops always around 477 frames.

I suppose is like u said some kind of bad video structure from the hauppauge hd pvr hardware h264 encoder ....

Trying to mess with some ffmpeg switches..... (maybe adding the ones used in the webM->h264 conversion command)

**Comment by vbence** [comment]
Yeah you can always transcode the stream to make sure the settings match, but it way cooler to stream directly from your hardware 😄 

`v4l2-ctl` should be able to control at least some aspects of your card's stream.

**Comment by vbence** [comment]
About the ports: yes, the HTTP server is at 8080, the RTMP at 8081. RTMP is there because it became de facto standard, and tools like OBS will handle it (they won't do long PUTs or POSTs).
