### ISSUE TITLE
Using Wirecast to Publish Stream

### ISSUE THREAD

**Issue by anthony-24** [vbence/stream-m#39]
Is there any documentation on how to setup Wirecast to publish stream to stream-m? Everything I've tried thus far fails to work. My last attempt was setting these fields in Wirecast:

Destination: RTMP Server
Address: rtmp://localhost:8081/publish
Stream: first
User Agent: Wirecast/FM 1.0

I set the credentials to the password, but do not specify a username. I am currently using Wirecast 6.0.6.

**Comment by vbence** [comment]
Hi, when using Wirecast it should be
Address: rtmp://localhost:8081/publish
Stream: first?secret
