### ISSUE TITLE
RTMP URL streamkey support

### ISSUE THREAD

**Issue by neuroscr** [vbence/stream-m#4]
To work with Flash Media Encoder and Open Broadcaster to stream RTMP, they take two parameters URL & StreamKey. Usually StreamKey is appended to the URL. This works in nginx-rtmp but not stream-m, I've tried various combinations that should give the same results. Any way of making stream-m accept the StreamKey as the password instead of the query parameter?

**Comment by vbence** [comment]
Sounds pretty straightforward. The current query string method was never meant to be final. Let me do a few trials with OBS...

**Comment by vbence** [comment]
I checked and it is a bit different from what I thought. In OBS you should give the following parameters (assuming the default):

**FMS URL:** `rtmp://127.0.0.1:8081/publish`
**Play Path / Streak Key:** `first?secret`

... so actually the URL is only the URL of the RTMP application. This is equal to the following URL (when you are using ffmpeg): rtmp://127.0.0.1:8081/publish/first?secret - the last part being the RTMP stream name which is processed by the application. The fact that is `streamName + "?" + password` is just a convention of Stream-m, but changing the "?" to "/" would not really make any difference.
