### ISSUE TITLE
Invalid .jar

### ISSUE THREAD

**Issue by DusanBrejka** [vbence/stream-m#44]
Hello,
it seems like neither the pre-release version "1.0-SNAPSHOT" downloaded from Github releases nor .jar file compiled myself is working. 

Error:
`no main manifest attribute, in stream-m-1.0-SNAPSHOT.jar`

The old release "v0.2.2" seems fine.

Can you please have a look into it?

**Comment by vbence** [comment]
Yes, I realized not long ago that the new gradle pipeline does not create manifest to find the main class.
Instead of `java -jar stream-m.jar` you can use
```
java -cp stream-m.jar org.czentral.incubator.streamm.Bootstrap
```

**Comment by vbence** [comment]
Fixed, the latest jar should contain the metadata.
