### ISSUE TITLE
org.czentral.minirtmp.RtmpException: Missing previous chunk

### ISSUE THREAD

**Issue by shinypebbles** [vbence/stream-m#48]
Hello Varga Bence,

I am experimenting with stream-m. I installed latest 1.0-SNAPSHOT from https://github.com/vbence/stream-m/releases on a Windows PC and started it with the template properties file: "C:\Program Files\Java\jdk-15.0.1\bin\java" -jar stream-m-1.0-SNAPSHOT.jar server.properties

I got the univac example working and also publishing webm to port 8080. Now I am trying to get publishing h.264 to work. 

When I run ffmpeg on Raspberry Pi as followes:
ffmpeg -f video4linux2 -s 320x240 -r 16 -i /dev/video0 -f oss \
-g 52 -strict experimental -acodec aac -ab 56k -vcodec libx264 -vb 452k \
-profile:v high -level 40 -r 16 \
-f flv "rtmp://serverhostname:8081/publish/first?secret"

On the server I get: 
org.czentral.minirtmp.RtmpException: Missing previous chunk (chunkId: 57, type: 3)
        at org.czentral.minirtmp.RtmpReader.read(RtmpReader.java:65)
        at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:95)
        at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:54)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:94)

I also tried it on a Windows client with:
c:\ffmpeg\bin\ffmpeg -f dshow -s 320x240 -r 16 ^
-i video="Logitech QuickCam Pro 9000":audio="Microfoon (Pro 9000)" ^
-g 52 -strict experimental -acodec aac -ab 56k -vcodec libx264 -vb 452k ^
-profile:v high -pix_fmt yuv420p -level 40 -r 16 ^
-f flv "rtmp://serverhostname:8081/publish/first?secret"

I get the same error:
org.czentral.minirtmp.RtmpException: Missing previous chunk (chunkId: 53, type: 1)
        at org.czentral.minirtmp.RtmpReader.read(RtmpReader.java:65)
        at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:95)
        at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:54)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:94)

Am I doing something wrong?

**Comment by vbence** [comment]
Hi shinypebbles, I think you're doing everything right. Let me try to reproduce it on my Raspberry. Could you check that the Raspi is detecting the webcam and it works in ffplay for VLC?

**Comment by shinypebbles** [comment]
The camera is detected. I don't get an error and the light goes on. This is the end of the output on the Pi:
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, start: 863.414755, bitrate: 14745 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 320x240, 14745 kb/s, 16 fps, 16 tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5344f0] using cpu capabilities: ARMv6 NEON
[libx264 @ 0x5344f0] profile High, level 4.0
[libx264 @ 0x5344f0] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=52 keyint_min=5 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=452 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, flv, to 'rtmp://serverhostname:8081/publish/first?secret':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (libx264) ([7][0][0][0] / 0x0007), yuv420p, 320x240, q=-1--1, 452 kb/s, 16 fps, 1k tbn, 16 tbc
    Metadata:
      encoder         : Lavc58.35.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/452000 buffer size: 0 vbv_delay: -1
frame=  223 fps= 16 q=18.0 size=     591kB time=00:00:10.62 bitrate= 455.8kbits/s speed=0.779x

**Comment by vbence** [comment]
I managed to reproduce this, although only after a few minutes of streaming. At the time I am getting the following on the ffmpeg side:
```
[dshow @ 0000022fc8b89dc0] real-time buffer [USB2.0 PC CAMERA] [video input] too full or near too full (65% of size: 3041280 [rtbufsize parameter])! frame dropped!
[dshow @ 0000022fc8b89dc0] real-time buffer [USB2.0 PC CAMERA] [video input] too full or near too full (75% of size: 3041280 [rtbufsize parameter])! frame dropped!
    Last message repeated 1 times
```
I'm not sure yet if this is a cause or a symptom.

**Comment by shinypebbles** [comment]
Yes, I saw that too:
`[dshow @ 0000020d65f4e900] real-time buffer [Logitech QuickCam Pro 9000] [video input] too full or near too full (106% of size: 3041280 [rtbufsize parameter])! frame dropped!`
Sorry, I didn't mention that.

**Comment by vbence** [comment]
Hi, can you please check if the latest snapshot solved the problem?

https://github.com/vbence/stream-m/releases/tag/untagged-7c8ac906f86d0ad0fa5c

**Comment by shinypebbles** [comment]
Hello Varga Bence,

Many thanks, It works now. Just a small suggestion for the read.me demo player section: You need to uncomment this lines in the server.properties file for the demo player to work:
`zip.player-demo = true
zip.player-demo.file = player-demo.zip
zip.player-demo.url = /player-demo`

Kind Regards,
