### ISSUE TITLE
Delay is tooo long

### ISSUE THREAD

**Issue by aegor** [vbence/stream-m#7]
For example, ffserver webm http delay is about 4 secs,
stream-m delay is about 40 secs
with this ffmpeg settings:
```
ffmpeg -f video4linux2 -video_size 320x240  -i /dev/video0 -g 52 \
-acodec libvorbis -ab 64k \
-vcodec libvpx -vb 448k -cpu-used 4 -quality realtime -bufsize 512 \
-f webm -cluster_time_limit 1000 "http://localhost:8080/publish/first?password=secret"
```
Note: The bufsize option linearly reduce delay in case of ffserver scenario.
In case of stream-m this option has no effect.
Ho to reduce internal buffer sizes or counts?
What buffers can affect these parameters?

**Comment by vbence** [comment]
I am using a fairly recent version of ffmpeg (built from git N-67806-g4eae568), and I'm getting a constant 6-8 sec of latency.

Do you have different results with the following command?

```
ffmpeg -f video4linux2 -video_size 320x240 -i /dev/video0 \
-acodec libvorbis -ab 64k -vsync cfr -r 20 -vcodec libvpx -vb 448k -g 52 \
-lag-in-frames 1 -slices 4 -deadline realtime -bufsize 512 \
-f webm "http://localhost:8080/publish/first?password=secret"
```

**Comment by aegor** [comment]
Confirm, 8 seconds! Thank you!

**Comment by vbence** [comment]
You're welcome.

It was probably the framerate of your webcam not being constant. `-vsync cfr` will enforce the `-r 20` parameter by duplicating/dropping frames.
