### ISSUE TITLE
Access-Control-Allow-Origin Header Missing

### ISSUE THREAD

**Issue by sqwk** [vbence/stream-m#8]
Is there an option to allow Cross Origin Requests for the MediaSource player?

```
Access-Control-Allow-Origin: *
```

Alternatively, fetch multiple allowed domains from the `server.properties` file.

**Comment by vbence** [comment]
Also needed `Access-Control-Expose-Headers` for the `X-Sequence` header if you are using the MediaSource player.

**Comment by sqwk** [comment]
Something along those lines? (in `HTTPResponse.java`)
 
    if (props.getProperty("crossorgin") === true) {
            parameters.put("Access-Control-Allow-Origin", "*");
            parameters.put("Access-Control-Expose-Headers", "X-Sequence");
    } else if (props.getProperty("crossorgin") !== false) {
            parameters.put("Access-Control-Allow-Origin", props.getProperty("crossorgin"));
            parameters.put("Access-Control-Expose-Headers", "X-Sequence");
    }

**Comment by vbence** [comment]
I would rather say

```
String crossOriginProp = props.getProperty("crossorgin", null);
if (crossOriginProp != null) {
        parameters.put("Access-Control-Allow-Origin", crossOriginProp);
        parameters.put("Access-Control-Expose-Headers", "X-Sequence");
}
```
